version: '3.8'

services:
  genhubbot:
    build: .
    container_name: genhubbot
    restart: unless-stopped
    environment:
      - GENHUB_GITHUB_TOKEN=${GENHUB_GITHUB_TOKEN}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    ports:
      - "8080:8080"
    volumes:
      - ./redbot-data:/home/redbot/redbot-data
      - .:/home/redbot/GenHubCog
      - ./GenHub:/home/redbot/.local/lib/python3.11/site-packages/redbot/cogs/GenHub
      - ./docker-entrypoint.sh:/home/redbot/docker-entrypoint.sh
    networks:
      - redbot-network

networks:
  redbot-network:
    driver: bridge
