import discord
import re

def clean_github_markdown(text: str, repo: str = None) -> str:
    """Clean and convert GitHub-specific HTML and markdown tags into clean Discord markdown."""
    if not text:
        return ""

    # 1. HTML entities decoding
    text = (
        text.replace("&quot;", '"')
        .replace("&apos;", "'")
        .replace("&#39;", "'")
        .replace("&#x27;", "'")
        .replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&nbsp;", " ")
    )

    # 2. Strip HTML comments <!-- ... -->
    text = re.sub(r"<!--[\s\S]*?-->", "", text)

    # 3. Strip promotional bot footers and social share blocks (CodeRabbit, Qodo, etc.)
    # Strip CodeRabbit footer block starting from "Thanks for using CodeRabbit" (with or without dashes/details)
    text = re.sub(
        r"(?:\n\s*[-*_]{3,}\s*)?\n\s*Thanks for using CodeRabbit[\s\S]*$",
        "",
        text,
        flags=re.IGNORECASE,
    )
    # Strip any standalone Share block (e.g. "❤️ Share:", "Share on:", "Share:")
    text = re.sub(
        r"(?:\n\s*[-*_]{3,}\s*)?\n\s*(?:[^\w\s]?\s*Share\s*:|Share\s+on\s*:)[\s\S]*$",
        "",
        text,
        flags=re.IGNORECASE,
    )
    # Strip Qodo / bot tips and promotional taglines
    text = re.sub(
        r"\n\s*(?:💡\s*Tip of the day|✨\s*Generated by Qodo|🐰\s*CodeRabbit)[\s\S]*$",
        "",
        text,
        flags=re.IGNORECASE,
    )
    # Strip command help line
    text = re.sub(
        r"\n\s*Comment\s+`?@coderabbitai\s+help`?[\s\S]*$",
        "",
        text,
        flags=re.IGNORECASE,
    )
    # Strip any leftover social intent URLs or share bullet items anywhere in text
    text = re.sub(
        r"(?:^[ \t]*[-*•]?[ \t]*\(?https?://(?:twitter\.com|x\.com|mastodon|linkedin|reddit)\.com/(?:intent|sharing|submit)[^\s)]*\)?[ \t]*\n?)+",
        "",
        text,
        flags=re.MULTILINE | re.IGNORECASE,
    )

    # 4. Badges, SVGs, and status icons transform BEFORE stripping tags
    # DeepSource Grade SVGs in picture/img tags: grade_a.svg -> [A]
    def replace_grade_svg(m):
        grade = m.group(1).upper()
        return f"[{grade}] "

    text = re.sub(
        r"<picture>[\s\S]*?grade_([a-zA-Z0-9+]+)\.svg[\s\S]*?</picture>\s*",
        replace_grade_svg,
        text,
        flags=re.IGNORECASE,
    )
    text = re.sub(
        r"<img[^>]*grade_([a-zA-Z0-9+]+)\.svg[^>]*>\s*",
        replace_grade_svg,
        text,
        flags=re.IGNORECASE,
    )

    # DeepSource Status SVGs: status_passed -> ✅ PASSED, status_failed -> ❌ FAILED, etc.
    text = re.sub(
        r"<picture>[\s\S]*?status_failed\.svg[\s\S]*?</picture>",
        "❌ FAILED",
        text,
        flags=re.IGNORECASE,
    )
    text = re.sub(
        r"<picture>[\s\S]*?status_passed\.svg[\s\S]*?</picture>",
        "✅ PASSED",
        text,
        flags=re.IGNORECASE,
    )
    text = re.sub(
        r"<picture>[\s\S]*?status_skipped\.svg[\s\S]*?</picture>",
        "⏭️ SKIPPED",
        text,
        flags=re.IGNORECASE,
    )
    text = re.sub(
        r"<picture>[\s\S]*?status_neutral\.svg[\s\S]*?</picture>",
        "⚪ NEUTRAL",
        text,
        flags=re.IGNORECASE,
    )
    text = re.sub(r"<img[^>]*status_failed\.svg[^>]*>", "❌ FAILED", text, flags=re.IGNORECASE)
    text = re.sub(r"<img[^>]*status_passed\.svg[^>]*>", "✅ PASSED", text, flags=re.IGNORECASE)
    text = re.sub(r"<img[^>]*status_skipped\.svg[^>]*>", "⏭️ SKIPPED", text, flags=re.IGNORECASE)

    # Shields.io badges (e.g. https://img.shields.io/badge/Medium-634FD1?style=flat-square -> `[Medium]`)
    text = re.sub(
        r"<img[^>]*src=[\"']https://img\.shields\.io/badge/([a-zA-Z0-9_%+-]+)-[a-zA-Z0-9_%+-]+[^\"']*[\"'][^>]*>",
        r"`[\1]`",
        text,
        flags=re.IGNORECASE,
    )
    # Remove decorative divider / spacer images
    text = re.sub(
        r"<img[^>]*alt=[\"'](?:Grey Divider|Divider|Line|spacer|separator)[\"'][^>]*>",
        "",
        text,
        flags=re.IGNORECASE,
    )
    # Remove decorative SVGs like grey lines or logos without useful alt
    text = re.sub(
        r"<img[^>]*(?:light-grey-line\.svg|qodo-logo\.svg)[^>]*>",
        "",
        text,
        flags=re.IGNORECASE,
    )
    # Generic img tags with alt text -> replace with alt text
    text = re.sub(
        r"<img[^>]*alt=[\"']([^\"']+)[\"'][^>]*>",
        r"\1",
        text,
        flags=re.IGNORECASE,
    )

    # Markdown linked images: [![alt](img_url)](link_url) -> [alt](link_url)
    def fix_md_linked_img(m):
        alt = m.group(1).strip()
        url = m.group(2).strip()
        link_title = alt if alt else "Link"
        return f"[{link_title}]({url})"

    text = re.sub(r"\[!\[([^\]]*)\]\([^)]+\)\]\(([^)]+)\)", fix_md_linked_img, text)
    # Standalone markdown images: ![alt](img_url) -> alt
    text = re.sub(r"!\[([^\]]*)\]\([^)]+\)", r"\1", text)

    # 5. HTML Tables formatting: cleanly convert <table> to Discord lines/bullets
    def format_html_table(match):
        table_content = match.group(1)
        rows = re.findall(r"<tr[^>]*>([\s\S]*?)</tr>", table_content, flags=re.IGNORECASE)
        if not rows:
            return ""
        table_lines = []
        for row in rows:
            headers = re.findall(r"<th[^>]*>([\s\S]*?)</th>", row, flags=re.IGNORECASE)
            cells = re.findall(r"<td[^>]*>([\s\S]*?)</td>", row, flags=re.IGNORECASE)
            if headers:
                clean_hdrs = [
                    re.sub(r"<[^>]+>", "", h).strip()
                    for h in headers
                    if re.sub(r"<[^>]+>", "", h).strip()
                ]
                if clean_hdrs:
                    table_lines.append("**" + " • ".join(clean_hdrs) + "**")
            elif cells:
                # Check if this row is a multi-item report card container (cells containing <br/><br/>)
                has_stacked_items = any(
                    re.search(r"<br\s*/?>\s*<br\s*/?>", c, re.IGNORECASE) for c in cells
                )
                if has_stacked_items:
                    for cell in cells:
                        parts = re.split(r"<br\s*/?>\s*<br\s*/?>", cell, flags=re.IGNORECASE)
                        for part in parts:
                            p = part.strip()
                            p = re.sub(
                                r'<a\s+[^>]*href=["\'](.*?)["\'][^>]*>(.*?)</a>',
                                lambda m: f"[{m.group(2).strip().strip('[]')}]({m.group(1).strip()})" if m.group(2).strip() else f"<{m.group(1).strip()}>",
                                p,
                                flags=re.IGNORECASE,
                            )
                            def format_strong_key(m):
                                key = m.group(1).rstrip(":").strip()
                                return f"**{key}**: "

                            p = re.sub(r"<(?:strong|b)>(.*?)</(?:strong|b)>\s*:?", format_strong_key, p, flags=re.IGNORECASE)
                            p = re.sub(r"<br\s*/?>", " ", p, flags=re.IGNORECASE)
                            p = re.sub(r"<[^>]+>", "", p)
                            p = re.sub(r"\s+", " ", p).strip()
                            if p:
                                table_lines.append(f"• {p}")
                else:
                    # Tabular columns
                    clean_cell_list = []
                    for cell in cells:
                        c = cell.strip()
                        c = re.sub(
                            r'<a\s+[^>]*href=["\'](.*?)["\'][^>]*>(.*?)</a>',
                            lambda m: f"[{m.group(2).strip().strip('[]')}]({m.group(1).strip()})" if m.group(2).strip() else f"<{m.group(1).strip()}>",
                            c,
                            flags=re.IGNORECASE,
                        )
                        c = re.sub(r"<strong>(.*?)</strong>", r"**\1**", c, flags=re.IGNORECASE)
                        c = re.sub(r"<b>(.*?)</b>", r"**\1**", c, flags=re.IGNORECASE)
                        c = re.sub(r"<br\s*/?>", " ", c, flags=re.IGNORECASE)
                        c = re.sub(r"<[^>]+>", "", c)
                        c = re.sub(r"\s+", " ", c).strip()
                        if c:
                            clean_cell_list.append(c)
                    if clean_cell_list:
                        if len(clean_cell_list) == 1:
                            table_lines.append(f"• {clean_cell_list[0]}")
                        elif len(clean_cell_list) == 2:
                            k, v = clean_cell_list[0], clean_cell_list[1]
                            k_clean = k.rstrip(":")
                            table_lines.append(f"• **{k_clean}**: {v}")
                        else:
                            table_lines.append("• " + " — ".join(clean_cell_list))
        return "\n" + "\n".join(table_lines) + "\n"

    text = re.sub(r"<table[^>]*>([\s\S]*?)</table>", format_html_table, text, flags=re.IGNORECASE)

    # 6. Markdown pipe tables conversion (e.g. Kilo overview tables)
    def format_markdown_table(match):
        raw_table = match.group(1).strip()
        lines = [l.strip() for l in raw_table.split("\n") if l.strip()]
        if len(lines) < 3:
            return raw_table
        headers = [c.strip() for c in lines[0].strip("|").split("|")]
        data_rows = []
        for line in lines[2:]:
            cells = [c.strip() for c in line.strip("|").split("|")]
            while len(cells) < len(headers):
                cells.append("")
            data_rows.append(cells[:len(headers)])

        out_lines = []
        if len(headers) == 2:
            for row in data_rows:
                k, v = row[0], row[1]
                if k:
                    out_lines.append(f"• **{k}**: {v}")
        else:
            clean_headers = [h for h in headers if h]
            if clean_headers:
                out_lines.append("**" + " • ".join(clean_headers) + "**")
            for row in data_rows:
                if any(row):
                    clean_cells = [c for c in row if c]
                    out_lines.append("• " + " — ".join(clean_cells))
        return "\n" + "\n".join(out_lines) + "\n"

    table_pattern = re.compile(
        r"(?:^|\n)([ \t]*\|[^\n]+\|\r?\n[ \t]*\|[-:\s|]+\|\r?\n(?:[ \t]*\|[^\n]+\|\r?\n?)+)",
        re.MULTILINE,
    )
    text = table_pattern.sub(format_markdown_table, text)

    # 7. HTML Headings and Horizontal Rules
    text = re.sub(r"<h[1-6][^>]*>(.*?)</h[1-6]>", r"\n### \1\n", text, flags=re.IGNORECASE)
    text = re.sub(r"<hr\s*/?>", "\n\n", text, flags=re.IGNORECASE)

    # 8. Convert <details><summary>
    text = re.sub(r"<summary>\s*<b>(.*?)</b>\s*</summary>", r"**\1:**", text, flags=re.IGNORECASE)
    text = re.sub(r"<summary>\s*<strong>(.*?)</strong>\s*</summary>", r"**\1:**", text, flags=re.IGNORECASE)
    text = re.sub(r"<summary>\s*(.*?)\s*</summary>", r"**\1:**", text, flags=re.IGNORECASE)
    text = re.sub(r"</?(?:details|summary)[^>]*>", "", text, flags=re.IGNORECASE)

    # 9. Normalize and clean blockquote prefixes (including indented ones)
    text = re.sub(r"^[ \t]*>[ \t]*", r"> ", text, flags=re.MULTILINE)

    # 10. GitHub Callouts / Alerts (> [!IMPORTANT], > [!NOTE], etc.)
    text = re.sub(
        r"^>[ \t]*\[!IMPORTANT\][ \t]*",
        r"> 🟣 **Important:** ",
        text,
        flags=re.MULTILINE | re.IGNORECASE,
    )
    text = re.sub(
        r"^>[ \t]*\[!NOTE\][ \t]*",
        r"> 📝 **Note:** ",
        text,
        flags=re.MULTILINE | re.IGNORECASE,
    )
    text = re.sub(
        r"^>[ \t]*\[!TIP\][ \t]*",
        r"> 💡 **Tip:** ",
        text,
        flags=re.MULTILINE | re.IGNORECASE,
    )
    text = re.sub(
        r"^>[ \t]*\[!WARNING\][ \t]*",
        r"> ⚠️ **Warning:** ",
        text,
        flags=re.MULTILINE | re.IGNORECASE,
    )
    text = re.sub(
        r"^>[ \t]*\[!CAUTION\][ \t]*",
        r"> 🚨 **Caution:** ",
        text,
        flags=re.MULTILINE | re.IGNORECASE,
    )
    # Standalone alerts without leading quote marker
    text = re.sub(
        r"^[ \t]*\[!IMPORTANT\][ \t]*",
        r"> 🟣 **Important:** ",
        text,
        flags=re.MULTILINE | re.IGNORECASE,
    )
    text = re.sub(
        r"^[ \t]*\[!NOTE\][ \t]*",
        r"> 📝 **Note:** ",
        text,
        flags=re.MULTILINE | re.IGNORECASE,
    )
    text = re.sub(
        r"^[ \t]*\[!TIP\][ \t]*",
        r"> 💡 **Tip:** ",
        text,
        flags=re.MULTILINE | re.IGNORECASE,
    )
    text = re.sub(
        r"^[ \t]*\[!WARNING\][ \t]*",
        r"> ⚠️ **Warning:** ",
        text,
        flags=re.MULTILINE | re.IGNORECASE,
    )
    text = re.sub(
        r"^[ \t]*\[!CAUTION\][ \t]*",
        r"> 🚨 **Caution:** ",
        text,
        flags=re.MULTILINE | re.IGNORECASE,
    )

    # 11. HTML Formatting to Markdown
    text = re.sub(r"<b>(.*?)</b>", r"**\1**", text, flags=re.IGNORECASE)
    text = re.sub(r"<strong>(.*?)</strong>", r"**\1**", text, flags=re.IGNORECASE)
    text = re.sub(r"<i>(.*?)</i>", r"*\1*", text, flags=re.IGNORECASE)
    text = re.sub(r"<em>(.*?)</em>", r"*\1*", text, flags=re.IGNORECASE)
    text = re.sub(r"<sub>(.*?)</sub>", r"*\1*", text, flags=re.IGNORECASE)
    text = re.sub(r"<sup>(.*?)</sup>", r"*\1*", text, flags=re.IGNORECASE)
    text = re.sub(r"<code>(.*?)</code>", r"`\1`", text, flags=re.IGNORECASE)
    text = re.sub(r"<kbd>(.*?)</kbd>", r"`\1`", text, flags=re.IGNORECASE)
    text = re.sub(r"</?(?:del|s|strike)>", "~~", text, flags=re.IGNORECASE)
    text = re.sub(r"<pre>([\s\S]*?)</pre>", r"\1", text, flags=re.IGNORECASE)
    text = re.sub(r"<br\s*/?>", "\n", text, flags=re.IGNORECASE)
    text = re.sub(r"</?p>", "\n", text, flags=re.IGNORECASE)
    text = re.sub(
        r'<a\s+[^>]*href=["\'](.*?)["\'][^>]*>(.*?)</a>',
        lambda m: f"[{m.group(2).strip().strip('[]')}]({m.group(1).strip()})" if m.group(2).strip() else f"<{m.group(1).strip()}>",
        text,
        flags=re.IGNORECASE,
    )

    # 12. Clean blockquotes <blockquote>...</blockquote>
    def format_blockquote(match):
        inner = match.group(1).strip()
        lines = inner.split("\n")
        quoted = []
        for l in lines:
            s = l.strip()
            if s.startswith(">"):
                quoted.append(s)
            elif s:
                quoted.append(f"> {s}")
            else:
                quoted.append(">")
        return "\n" + "\n".join(quoted) + "\n"

    text = re.sub(r"<blockquote>([\s\S]*?)</blockquote>", format_blockquote, text, flags=re.IGNORECASE)

    # 13. Remove any remaining unhandled HTML tags
    text = re.sub(r"</?[a-zA-Z0-9_-]+(?:\s+[^>]*)?>", "", text)

    # 14. Fix empty or pseudo markdown links
    def fix_empty_link(match):
        url = match.group(1).strip()
        if "deepsource.com" in url:
            return f"[DeepSource Report](<{url}>)"
        if "github.com" in url:
            return f"[GitHub Link](<{url}>)"
        return f"[Link](<{url}>)"

    text = re.sub(r"\[\s*\]\(([^)]+)\)", fix_empty_link, text)
    # Convert invalid/pseudo markdown links (e.g. [coderabbitai](coderabbitai) -> `coderabbitai`)
    text = re.sub(r"\[([^\]]+)\]\((?!(?:https?|mailto):|/|#)([^)]+)\)", r"`\1`", text)

    # 15. Convert GitHub task list checkboxes with bullet alignment: [ ] -> ⬜, [x] -> ☑️
    text = re.sub(r"^\s*[-*•]?\s*\[\s*\]\s*", r"• ⬜ ", text, flags=re.MULTILINE)
    text = re.sub(r"^\s*[-*•]?\s*\[[xX]\]\s*", r"• ☑️ ", text, flags=re.MULTILINE)

    # 16. Format standalone horizontal rules (---, ***, ___) cleanly into spacing rather than raw dashes
    text = re.sub(r"(?:^|\n)[ \t]*[-*_]{3,}[ \t]*(?:\n|$)", "\n\n", text)

    # 17. MASK code blocks, inline code, and existing markdown links before auto-linking
    placeholders = []
    def mask_match(m):
        placeholders.append(m.group(0))
        return f"\x00MASK_{len(placeholders) - 1}\x00"

    # Mask fenced code blocks
    text = re.sub(r"```[\s\S]*?```", mask_match, text)
    # Mask inline code spans
    text = re.sub(r"`[^`\n]+`", mask_match, text)
    # Mask markdown links [text](url)
    text = re.sub(r"\[[^\]]+\]\([^)]+\)", mask_match, text)

    # 18. Auto-link repository issues/PRs (e.g. community-outpost/GenHub#267) safely on unmasked text
    text = re.sub(
        r"\b([a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+)#(\d+)\b",
        r"[\1#\2](https://github.com/\1/issues/\2)",
        text,
    )

    # 19. Auto-link standalone #123 if repo context is provided safely on unmasked text
    if repo:
        clean_repo = repo.strip().lstrip("/")
        text = re.sub(
            r"(?<![a-zA-Z0-9_./&#])#(\d+)\b",
            rf"[#\1](https://github.com/{clean_repo}/issues/\1)",
            text,
        )

    # 20. Unmask preserved code and links in REVERSE order to handle nesting safely
    for idx, orig in reversed(list(enumerate(placeholders))):
        text = text.replace(f"\x00MASK_{idx}\x00", orig)

    # 21. Clean status suffixes like [merged], [open], [closed] to prevent markdown collision
    text = re.sub(r"\[(merged|open|closed|draft)\](?!\()", r"(\1)", text, flags=re.IGNORECASE)

    # 22. Clean up blockquotes: collapse redundant empty quote lines (> \n > \n >)
    text = re.sub(r"(\n>[ \t]*){2,}", r"\n> ", text)
    # Ensure space after > if followed by non-whitespace (e.g. >Description: -> > Description:)
    text = re.sub(r"^>([^\s>])", r"> \1", text, flags=re.MULTILINE)

    # 23. Clean excessive empty lines
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def summarize_bot_body(body: str, max_chars: int = 280) -> str:
    """Extract a clean, ultra-compact executive summary from bot comments/reviews."""
    if not body or not body.strip():
        return "*Automated code review submitted on GitHub.*"

    # Convert markdown headers (#, ##, ###) into bold text
    text = re.sub(r"^[#]+\s*(.+)$", r"**\1**", body, flags=re.MULTILINE)

    lines = [line.strip() for line in text.splitlines() if line.strip()]
    summary_lines = []
    current_len = 0

    for line in lines:
        if line.startswith("---") or line.startswith("***") or line.startswith("___"):
            continue
        if line.startswith("|") or line.startswith("```") or line.startswith("<details") or line.startswith("</details"):
            continue
        if current_len + len(line) > max_chars:
            remaining = max_chars - current_len - 3
            if remaining > 25:
                summary_lines.append(line[:remaining].rstrip() + "...")
            break
        summary_lines.append(line)
        current_len += len(line)
        if len(summary_lines) >= 3:
            break

    summary = "\n".join(summary_lines).strip()
    return summary if summary else (body[:max_chars].rstrip() + "...")


def create_comment_embed(
    author: str,
    body: str,
    url: str,
    author_icon: str = None,
    is_bot: bool = False,
    is_review: bool = False,
    extra_count: int = 0,
    created_at: str = None,
    repo: str = None,
) -> discord.Embed:
    """Create a sleek Discord Embed for a GitHub issue or review comment with timestamp."""
    import datetime
    clean_body = clean_github_markdown(body, repo=repo)

    if is_bot:
        clean_body = summarize_bot_body(clean_body, max_chars=280)
        color = 0x2B2D31 if is_review else 0x383A40
        role_label = "Bot Review" if is_review else "Bot Notice"
        if extra_count > 0:
            callout = f"\n\n> 💬 **{extra_count} inline automated review findings** on GitHub."
            clean_body = clean_body + callout
            footer_text = f"🤖 {extra_count} additional automated comments on GitHub"
        else:
            footer_text = "🤖 Automated Bot Notice"
    else:
        if len(clean_body) > 2040:
            clean_body = clean_body[:1950].rstrip() + f"\n\n... *([Read full comment on GitHub](<{url}>))*"
        color = 0x5865F2
        role_label = "Comment"
        footer_text = "GitHub Comment"

    embed = discord.Embed(
        description=clean_body if clean_body else "*Empty comment body*",
        color=color,
    )
    author_name = f"{author} ({role_label})"
    embed.set_author(
        name=author_name[:256],
        url=url,
        icon_url=author_icon if author_icon else "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
    )

    # Attach creation timestamp if available
    if created_at:
        try:
            ts_str = str(created_at).replace("Z", "+00:00")
            embed.timestamp = datetime.datetime.fromisoformat(ts_str)
        except Exception:
            pass

    embed.set_footer(text=footer_text)
    return embed


def create_review_link_view(url: str, count: int) -> discord.ui.View:
    """Create an interactive link button view to inspect extra inline review comments on GitHub."""
    view = discord.ui.View(timeout=None)
    label = f"View {count} Inline Review Comments" if count > 1 else "View Inline Review Comment"
    button = discord.ui.Button(
        style=discord.ButtonStyle.link,
        label=label[:80],
        url=url,
        emoji="🔍",
    )
    view.add_item(button)
    return view


async def send_message(channel, content: str = "", prefix: str = "", embed: discord.Embed = None, view: discord.ui.View = None):
    """Send a message or embed with optional interactive View, splitting long text into chunks if needed."""
    if embed:
        if view:
            await channel.send(embed=embed, view=view)
        else:
            await channel.send(embed=embed)
        return

    limit = 2000
    allowed_mentions = discord.AllowedMentions(
        roles=True, users=True, everyone=True
    )

    if len(prefix) > limit:
        prefix = prefix[: limit - 3] + "..."

    chunks = [content[i : i + limit] for i in range(0, len(content), limit)]

    for i, chunk in enumerate(chunks):
        is_last = (i == len(chunks) - 1)
        v = view if is_last else None
        if i == 0 and prefix:
            available = limit - len(prefix)
            if len(chunk) > available:
                await channel.send(
                    prefix + chunk[:available], allowed_mentions=allowed_mentions
                )
                remainder = chunk[available:]
                for j in range(0, len(remainder), limit):
                    sub_last = is_last and (j + limit >= len(remainder))
                    await channel.send(
                        remainder[j : j + limit], allowed_mentions=allowed_mentions, view=(view if sub_last else None)
                    )
            else:
                await channel.send(
                    prefix + chunk, allowed_mentions=allowed_mentions, view=v
                )
        else:
            await channel.send(chunk, allowed_mentions=allowed_mentions, view=v)


def get_role_mention(guild, role_id: int):
    """Resolve a role mention safely."""
    if not role_id:
        return ""
    role = guild.get_role(role_id)
    return role.mention if role else ""


def is_bot_author(author_login: str, user_data: dict = None) -> bool:
    """Determine if a GitHub author is an automated bot."""
    if not author_login:
        return False
    if user_data and user_data.get("type") == "Bot":
        return True
    login_lower = author_login.lower().strip()
    if login_lower.endswith("[bot]"):
        return True
    known_bots = {
        "coderabbitai",
        "coderabbitai[bot]",
        "deepsource-autofix",
        "deepsource-autofix[bot]",
        "deepsource[bot]",
        "github-actions",
        "github-actions[bot]",
        "kilo-code-review",
        "kilo-code-review[bot]",
        "greptile-ai",
        "greptile-ai[bot]",
        "codecov",
        "codecov[bot]",
        "dependabot",
        "dependabot[bot]",
        "sonarcloud",
        "sonarcloud[bot]",
        "linear",
        "linear[bot]",
        "vercel",
        "vercel[bot]",
        "snyk-bot",
        "renovate",
        "renovate[bot]",
    }
    return login_lower in known_bots



def format_message(emoji, action, title, url, author, role_mention, extra="", number=None):
    """Format a standard message for issues/PRs with clickable title/number."""
    display_title = title
    if number is not None and not str(title).strip().startswith(f"#{number}") and not str(title).strip().startswith(f"[#{number}]"):
        display_title = f"#{number} {title}"
    msg = f"{emoji} {action}: [{display_title}]({url})\n"
    msg += f"👤 By: {author} {role_mention}"
    if extra:
        msg += f"\n{extra}"
    return msg


async def get_or_create_tag(forum, name):
    """Find or create a tag by name (case-insensitive)."""
    for tag in forum.available_tags:
        if tag.name.lower() == name.lower():
            return tag
    try:
        return await forum.create_tag(name=name, moderated=False)
    except Exception as e:
        print(f"⚠️ Failed to create tag '{name}' in {forum.name}: {e}")
        return None


async def get_issue_tags(forum, issue):
    tags = []
    if not forum:
        return tags
    state = issue.get("state", "open")
    if str(state).lower() == "open":
        tag = await get_or_create_tag(forum, "Open")
    else:
        tag = await get_or_create_tag(forum, "Closed")
    if tag:
        tags.append(tag)
    if issue.get("assignees") or issue.get("assignee"):
        active_tag = await get_or_create_tag(forum, "Active")
        if active_tag:
            tags.append(active_tag)
    return tags


async def get_pr_tags(forum, pr):
    tags = []
    if not forum:
        return tags
    state = pr.get("state", "open")
    if str(state).lower() == "open":
        tag = await get_or_create_tag(forum, "Open")
    elif pr.get("merged") or pr.get("merged_at") or (
        "pull_request" in pr and pr["pull_request"].get("merged_at")
    ):
        tag = await get_or_create_tag(forum, "Merged")
    else:
        tag = await get_or_create_tag(forum, "Closed")
    if tag:
        tags.append(tag)
    if pr.get("assignees") or pr.get("assignee"):
        active_tag = await get_or_create_tag(forum, "Active")
        if active_tag:
            tags.append(active_tag)
    return tags


async def update_status_tag(thread, new_status_name):
    """Replace status tag while preserving repo tag."""
    forum = thread.parent
    new_status_tag = await get_or_create_tag(forum, new_status_name)
    if not new_status_tag:
        return
    current_tags = list(thread.applied_tags)
    status_names = {"open", "closed", "merged", "active"}
    current_tags = [t for t in current_tags if t.name.lower() not in status_names]
    current_tags.append(new_status_tag)
    await thread.edit(applied_tags=current_tags)


async def find_thread(bot, forum_id, repo_full_name, topic_number, thread_cache):
    """Find an existing thread by repo + number."""
    # First check cache for a valid thread
    keys_to_try = [
        (forum_id, repo_full_name, topic_number),
        (str(forum_id), repo_full_name, topic_number),
        f"{forum_id}:{repo_full_name}:{topic_number}",
    ]
    for k in keys_to_try:
        if k in thread_cache:
            cached = thread_cache[k]
            # If we stored a thread object, do a quick validation
            if hasattr(cached, "id"):
                try:
                    # Quick validation - try to access a property that would fail if deleted
                    if hasattr(cached, 'name'):
                        _ = cached.name  # This should fail if the thread is deleted
                        # Also check if the thread is accessible by trying to get its ID
                        _ = cached.id
                    return cached
                except (AttributeError, discord.NotFound, discord.Forbidden):
                    # Thread is invalid/stale/deleted, remove from cache
                    print(f"🗑️ Removing stale thread #{topic_number} from cache")
                    del thread_cache[k]
                    continue

    forum = bot.get_channel(forum_id)
    if not forum and hasattr(bot, "fetch_channel"):
        try:
            forum = await bot.fetch_channel(forum_id)
        except Exception:
            pass

    if not forum:
        return None

    # Get repository short name for pattern matching
    repo_short_name = repo_full_name.split('/')[-1]

    # Try patterns: first with new format, then legacy patterns for backward compatibility
    patterns = [
        rf"\[GH\] \[#{topic_number}\](?:\s|$)",  # New format: [GH] [#NUMBER]
        rf"「{re.escape(repo_short_name)}#{topic_number}」(?:\D|$)",  # Old format with corner brackets
        rf"{re.escape(repo_short_name)}#{topic_number}(?:\D|$)",
        rf"「#{topic_number}」(?:\D|$)",  # Legacy pattern for backward compatibility
        rf"#{topic_number}(?:\D|$)",
        rf"{topic_number}(?:\D|$)",
    ]

    # Collect candidate threads from forum and guild
    candidate_threads = []
    threads_attr = getattr(forum, "threads", [])
    try:
        if threads_attr:
            for t in threads_attr:
                if t not in candidate_threads:
                    candidate_threads.append(t)
    except (TypeError, Exception):
        pass

    guild = getattr(forum, "guild", None)
    if guild and hasattr(guild, "threads"):
        try:
            for t in guild.threads:
                if getattr(t, "parent_id", None) == forum_id or getattr(t, "parent", None) == forum:
                    if t not in candidate_threads:
                        candidate_threads.append(t)
        except Exception:
            pass

    for pattern in patterns:
        for thread in candidate_threads:
            try:
                name = getattr(thread, "name", "")
                if re.match(pattern, name):
                    thread_cache[(forum_id, repo_full_name, topic_number)] = thread
                    thread_cache[(str(forum_id), repo_full_name, topic_number)] = thread
                    return thread
            except Exception:
                continue

        if hasattr(forum, "archived_threads"):
            try:
                async for thread in forum.archived_threads(limit=100):
                    name = getattr(thread, "name", "")
                    if re.match(pattern, name):
                        thread_cache[(forum_id, repo_full_name, topic_number)] = thread
                        thread_cache[(str(forum_id), repo_full_name, topic_number)] = thread
                        return thread
            except (TypeError, AttributeError, Exception):
                pass

    return None


async def get_or_create_thread(
    bot, forum_id, repo_full_name, number, title, url, tags, thread_cache, initial_content=None
):
    # First try to find an existing thread
    existing = await find_thread(bot, forum_id, repo_full_name, number, thread_cache)
    if existing:
        print(f"📝 Found existing thread #{number} for {repo_full_name}")
        # Check if thread is archived - if so, recreate as active for reconcile
        if hasattr(existing, 'archived') and existing.archived:
            print(f"ℹ️ Found archived thread #{number}, recreating as active")
            # Remove from cache and treat as not found to force recreation
            keys_to_remove = [
                (forum_id, repo_full_name, number),
                (str(forum_id), repo_full_name, number),
                f"{forum_id}:{repo_full_name}:{number}",
            ]
            for key in keys_to_remove:
                thread_cache.pop(key, None)
            existing = None  # Force recreation
        else:
            # Validate thread is still accessible with more robust checks
            try:
                _ = existing.id

                if hasattr(existing, 'channel'):
                    _ = existing.channel

                if hasattr(existing, 'name'):
                    _ = existing.name

                try:
                    async for message in existing.history(limit=1):
                        break
                except (discord.NotFound, discord.Forbidden):
                    raise discord.NotFound("Thread history inaccessible")

                # Update name if it doesn't match expected (capped to 100 chars)
                expected_name = f"[GH] [#{number}] {title}"[:100]
                if hasattr(existing, 'name') and existing.name != expected_name:
                    try:
                        await existing.edit(name=expected_name)
                        print(f"📝 Updated thread name for #{number}")
                    except (discord.Forbidden, discord.NotFound):
                        print(f"⚠️ Could not update thread name for #{number}, recreating")
                        keys_to_remove = [
                            (forum_id, repo_full_name, number),
                            (str(forum_id), repo_full_name, number),
                            f"{forum_id}:{repo_full_name}:{number}",
                        ]
                        for key in keys_to_remove:
                            thread_cache.pop(key, None)
                        existing = None
            except (discord.NotFound, discord.Forbidden) as e:
                print(f"⚠️ Thread #{number} appears to be deleted or inaccessible ({type(e).__name__}), recreating")
                keys_to_remove = [
                    (forum_id, repo_full_name, number),
                    (str(forum_id), repo_full_name, number),
                    f"{forum_id}:{repo_full_name}:{number}",
                ]
                for key in keys_to_remove:
                    thread_cache.pop(key, None)
                existing = None
            except AttributeError as e:
                if "discord" in str(type(existing)).lower():
                    print(f"⚠️ Thread #{number} appears to be invalid ({type(e).__name__}), recreating")
                    keys_to_remove = [
                        (forum_id, repo_full_name, number),
                        (str(forum_id), repo_full_name, number),
                        f"{forum_id}:{repo_full_name}:{number}",
                    ]
                    for key in keys_to_remove:
                        thread_cache.pop(key, None)
                    existing = None

    if existing:
        return existing, False

    forum = bot.get_channel(forum_id)
    if not forum and hasattr(bot, "fetch_channel"):
        try:
            forum = await bot.fetch_channel(forum_id)
        except Exception:
            pass

    if not forum:
        print(f"⚠️ Could not find forum {forum_id}")
        return None, False

    # Create thread name with repository, capped strictly to Discord's 100 character maximum
    thread_name = f"[GH] [#{number}] {title}"[:100]

    print(f"🔄 Creating new thread for {repo_full_name}#{number}")
    try:
        content = initial_content if initial_content else f"🆕 Issue created: [{title}]({url})\n👤 By: Unknown"

        thread_with_msg = await forum.create_thread(
            name=thread_name,
            content=content,
            applied_tags=tags,
        )
        print(f"✅ Created new thread for {repo_full_name}#{number}")
    except discord.Forbidden:
        print(f"⚠️ Missing permissions to create thread in {forum.name}")
        return None, False
    except Exception as e:
        print(f"⚠️ Failed to create thread for {repo_full_name}#{number}: {e}")
        return None, False

    thread = getattr(thread_with_msg, "thread", thread_with_msg)
    key_tuple_int = (forum_id, repo_full_name, number)
    key_tuple_str = (str(forum_id), repo_full_name, number)
    thread_cache[key_tuple_int] = thread
    thread_cache[key_tuple_str] = thread
    return thread, True


def find_associated_chat_channel(guild, forum_channel, is_pr: bool):
    """Heuristically discover the accompanying text chat channel for a forum feed."""
    if not guild or not forum_channel:
        return None

    category = getattr(forum_channel, "category", None)
    keywords = (
        ["pr", "pull-request", "pull_request", "pulls", "prs"]
        if is_pr
        else ["issue", "issues", "bugs", "bug", "tickets", "feedback"]
    )

    # 1. Search text channels inside the SAME category first
    if category and hasattr(category, "text_channels"):
        for ch in category.text_channels:
            name = ch.name.lower().replace("-", "").replace("_", "").replace(" ", "")
            for kw in keywords:
                clean_kw = kw.replace("-", "").replace("_", "")
                if clean_kw in name:
                    return ch

    # 2. Search all text channels in the guild with "chat" in name
    if hasattr(guild, "text_channels"):
        for ch in guild.text_channels:
            name = ch.name.lower().replace("-", "").replace("_", "").replace(" ", "")
            for kw in keywords:
                clean_kw = kw.replace("-", "").replace("_", "")
                if clean_kw in name and "chat" in name:
                    return ch

        # 3. Search all text channels in the guild matching keywords
        for ch in guild.text_channels:
            name = ch.name.lower().replace("-", "").replace("_", "").replace(" ", "")
            for kw in keywords:
                clean_kw = kw.replace("-", "").replace("_", "")
                if clean_kw in name:
                    return ch

    return None


def find_associated_updates_channel(guild, forum_channel=None):
    """Heuristically discover a pinned updates / announcements channel or thread."""
    if not guild:
        return None

    keywords = ["pinnedupdates", "pinnedupdate", "updates", "pinned", "announcements", "developmentupdates", "devupdates"]

    # 1. Search inside the same category if forum provided
    if forum_channel:
        category = getattr(forum_channel, "category", None)
        if category and hasattr(category, "channels"):
            for ch in category.channels:
                name = ch.name.lower().replace("-", "").replace("_", "").replace(" ", "")
                for kw in keywords:
                    if kw in name:
                        return ch

    # 2. Search all channels in guild
    if hasattr(guild, "channels"):
        for ch in guild.channels:
            name = ch.name.lower().replace("-", "").replace("_", "").replace(" ", "")
            for kw in keywords:
                if kw in name:
                    return ch

    return None


