name: GenHub CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
          pip install pytest pytest-asyncio coverage aiohttp "discord.py>=2.3.2"

      - name: Run tests with coverage
        env:
          PYTHONPATH: .
        run: |
          coverage run -m pytest -v --maxfail=1 --disable-warnings
          coverage report --fail-under=90 -m
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
